<?php

// Color option
Redux::setSection('manohar_opt', array(
	'title'     => esc_html__('Colors', 'manohar'),
	'id'        => 'color',
	'icon'      => 'dashicons dashicons-admin-appearance',
	'fields'    => array(
		array(
			'id'          => 'accent_gradient',
			'type'        => 'color_gradient',
			'title'       => esc_html__( 'Gradient color', 'manohar' ),
			'default'     => array(
			    'from' => '#ff5f6d',
			    'to' => '#ffc371',
            ),
		),
		array(
			'id'        => 'accent_solid_color',
			'type'      => 'color',
			'title'     => esc_html__( 'Accent Solid Color', 'manohar' ),
			'output'    => array(
			    'color' => '
			        .woocommerce div.product p.price, .woocommerce div.product span.price,
			        .counter h2,
			        .view-style div a:hover i, .pink-color,
			        .view-style .active i, .solid_color:hover,
			        .single_product_item .product_quary,
			        .single_product_item .single_pr_details:hover h2,
			        .woocommerce span.onsale,
			        .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart + .btn-cart,
			        .recent-post-widget .post-sm-content a:hover h6, .widget_archive ul li a:hover, 
			        .widget_categories ul li a:hover, .widget_meta ul li a:hover, 
			        .widget_nav_menu ul li a:hover, .widget_pages ul li a:hover, .widget_recent_entries ul li a:hover,
			        .skew-bg .single-portfolio h1,
			        .portfolio_two .portfolio-description .links, .portfolio_two .portfolio-details li a:hover,
			        .navbar .attr-nav ul li.dropdown.cart-menu a .cart,
			        a.readmore:hover span,
			        .shop_sidebar ul li a:hover,
			        .woocommerce .woocommerce-widget-layered-nav-list .woocommerce-widget-layered-nav-list__item:hover a,
			        .woocommerce .woocommerce-widget-layered-nav-list .woocommerce-widget-layered-nav-list__item:hover span,
			        .rounded-image .inline-btn .btn.btn-outline-white,
			        .woocommerce .star-rating span::before,
			        .woocommerce .star-rating::before,
			        .woocommerce ul.product_list_widget li a span:hover,
			        .post-info a:hover, .post-content a:hover,
			        .post-info h6.pink-color,
			        a:hover.readmore,
			        a:hover, a:focus,
                    .default-color,
                    .gallery-style-two .portfolio-description .links,
                    .portfolio-description .links,
                    .post-info .post-meta li a:hover,
                    .blog-grid-video .video-blog .video-play,
                    .posts_social .pull-left a:hover,
                    .posts_social .pull-right a:hover,
                    .post-sm-content h6:hover,
                    .l_footer_area .footer-main ul.social-media li a:hover, 
                    .l_footer_area.footer .widget-links a:hover, .l_footer_area .post-sm-content a h6:hover,
                    .widget-copy .copy-right .pink-color,
                    .s_content .service_list li i,
                    .service_video .video-play,
                    .memder_details .about_details li a:hover,
                    .memder_details .social_icon a:hover,
                    .shop_list .panel .panel-heading .panel-title a i,
                    .single_product_item .product_quary.pr_red,
                    .single_product_item .single_pr_details .pr_rating i,
                    .filter_slider_area .filter_content .button_b,
                    .s_subscribe_form i,
                    .shop_menu_right .bootstrap-select .btn-default .caret:before,
                    .product_details .product_info .rating a:nth-child(1), 
                    .product_details .product_info .rating a:nth-child(2),
                    .product_details .product_info .review a,
                    .product_details .price,
                    .product_details .product_meta li span,
                    .product_details .product_meta li span a:hover,
                    .product_details .share-link .social-icon li a:hover,
                    .product-qty button:hover,
                    .pr_description-tab .nav-tabs li.active a, .pr_description-tab .nav-tabs li:hover a,
                    .review_tab .media .media-body .rating a,
                    .review_form .form-submit .rating a:nth-child(2), 
                    .review_form .form-submit .rating a:nth-child(3),
                    .cart_total_box ul li.payment span,
                    .cart_total_box ul li .l_text a,
                    .return_customer a,
                    .search_item .search_meta li a:hover,
                    .search_item h3:hover,
                    .search_sidebar_widget .widget_archive ul li a:hover, 
                    .search_sidebar_widget .widget_categories ul li a:hover, 
                    .search_sidebar_widget .widget_archive ul li a:hover,
                    .c_footer a:hover,
                    .c_footer p a,
                    .footer a,
                    .portfolio_category ul li a:hover,
                    .footer .widget-links a:hover,
                    .footer-main ul.social-media li a:hover,
                    ul.footer-contact li i,
                    .por_pagination_btn:hover,
                    .navbar .nav li.dropdown .dropdown-menu li:hover > a,
                    .has-error .help-block, .has-error .control-label, .has-error .radio, .has-error .checkbox, 
                    .has-error .radio-inline, .has-error .checkbox-inline, .has-error.radio label, 
                    .has-error.checkbox label, .has-error.radio-inline label, .has-error.checkbox-inline label,
                    .navbar .nav li.active .dropdown-menu li.active a, .navbar .nav li.open .dropdown-menu li.active a,
                    .header_area.affix .navbar .nav li.active > a, .header_area.affix .navbar .nav li.open > a,
                    .header_area.affix .navbar .nav li:hover > a,
                    .widget-contact p a:hover,
                    .play-button:hover,
                    .inline_btn_three p,
                    .testimonial-item h6,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart-single-item a:hover,
                    .white-color .call-us h5,
                    .pink-color,
                    .portfolio-details li a:hover,
                    .member-icons li a:hover,
                    .post-info a:hover, .post-content a:hover,
                    .post-info h6.pink-color,
                    .btn.btn_white,
                    a:hover.readmore,
                    .btn.read-more,
                    .heading-style-one h6,
                    .heading-style-two h6,
                    .inline_btn_two p, .more_btn,
                    .feature-box-three .btn-sm,
                    .header_three .navbar .attr-nav ul li.dropdown.cart-menu > a .cart,
                    .woocommerce .widget_price_filter .price_slider_amount .button,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart:hover,
                    #contact-form .btn.btn-candy:hover, .comment-form .btn.btn-candy:hover
                    ',
                'background-color' => '
                    .woocommerce .widget_price_filter .ui-slider .ui-slider-range,
                    .portfolio_two .portfolio-description h3:after,
                    .slider_two .default-slider .slick-dots li.slick-active button,
                    .slider_five .default-slider .slick-dots li.slick-active button,
                    .woocommerce nav.woocommerce-pagination ul li a:focus, 
                    .woocommerce nav.woocommerce-pagination ul li a:hover, 
                    .woocommerce nav.woocommerce-pagination ul li span.current,
                    .header_area .navbar .nav li.active > a:before, .header_area .navbar .nav li.open>a:before,
                    .tinv-wishlist .button.tinvwl_add_to_wishlist_button.tinvwl-icon-heart-plus:hover,
                    .testimonial_two_yellow .slick-dots li:not(.slick-active) button,
                    .header_area.affix .navbar .attr-nav ul li a .cart,
                    .navbar .nav li.current-menu-ancestor > a:before,
                    .woocommerce #payment #place_order, .woocommerce-page #payment #place_order,
                    .woocommerce .widget_price_filter .ui-slider .ui-slider-handle:before,
                    .navbar .nav li > a:before,
                    .navbar .nav li.current-menu-item > a:before,
                    .navbar .nav li.active .dropdown-menu li.active a:before, 
                    .navbar .nav li.open .dropdown-menu li.active a:before,
                    .heading-style-two h2.purple_br span:after,
                    .header_area.affix .navbar .nav li.active > a:before, 
                    .header_area.affix .navbar .nav li.open > a:before,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart,
                    .testimonial_four .slick-dots li.slick-active button,
                    .testimonial_four .slick-dots li button:hover,
                    .inline_btn_three .popup-youtube,
                    .footer-two .pink-color.widget-title:before, .comment-form-title:before,
                    .blog-grid-video .video-blog .video-play:hover,
                    .gallery-style-two .portfolio-description h3:after, 
                    .thin-border-purple,
                    .tagcloud a:hover,
                    .pagination li.active:hover a, .pagination li:hover:hover a, .pagination li:focus:hover a,
                    .post-comment .reply a:hover,
                    .l_footer_area .widget-title:before,
                    .port_skilll .progress .progress-bar,
                    .team_one .team_image:before,
                    .single_product_item .hover_content a:hover,
                    .filter_slider_area .ui-slider .ui-slider-range,
                    .filter_slider_area .ui-slider .ui-slider-handle:before,
                    .s_subscribe_form .subcribes .input-group-btn,
                    .product_details .cart_button .cart_btn:hover, .product_details .cart_button .wish_list:hover,
                    .cart_table tbody tr td.del-item i:hover,
                    .cupon_box button:hover,
                    .cart_total_box ul .radio-btn label:after,
                    .cart_total_box .proceed_to_checkout .thm-btn:hover,
                    .cart_total_box .proceed_to_checkout .thm-btn.thm-btn-two,
                    .checkout_content .login_form .btn-default:hover,
                    .cart_btn:hover,
                    .search_btn,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart + .btn-cart:hover,
                    .portfolio-description h3:after,
                    .btn.btn_white:hover,
                    .blog-grid-video .video-blog .video-play:hover,
                    .header_area.affix .navbar .nav li:hover > a:before,
                    .btn.back_btn,
                    .navbar .nav li.dropdown .dropdown-menu li:hover > a:before,                    
                    .feature-box-three .btn-sm:hover,
                    .inline_btn_two .popup-youtube,
                    .single-portfolio-title-right h2:after, .single-portfolio-title-left h2:after,
                    .more_btn:hover, .more_btn:focus,
                    .testimonial_two_yellow .slick-dots li.slick-active button,
                    .testimonial_two_yellow .slick-dots li:hover button,
                    .testimonial_two_yellow .slick-dots li.slick-active button, 
                    .testimonial_two_yellow .slick-dots li:hover button,
                    #contact-form .btn.btn-candy, .comment-form .btn.btn-candy,
                    .page-numbers li span.page-numbers.current, .pagination span.page-numbers.current, .pagination .page-numbers:hover,
                    .btn.read-more:hover
                    ',
                'border-color'  => '
                    .post-comment .reply a:hover,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart:hover,
                    .tagcloud a:hover, .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart + .btn-cart,
                    .single_product_item .product_quary,
                    .page-numbers li span.page-numbers.current, .pagination span.page-numbers.current, .pagination .page-numbers:hover,
                    a.readmore:hover span,
                    .blog_list a.readmore:hover span,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart + .btn-cart:hover,
                    .woocommerce .widget_price_filter .ui-slider .ui-slider-handle,
                    .woocommerce .widget_price_filter .price_slider_amount .button,
                    .navbar .attr-nav ul li.dropdown.cart-menu .cart_f .btn-cart,
                    .pagination li.active:hover a, .pagination li:hover:hover a, .pagination li:focus:hover a,
                    .widget-contact h1:before,
                    .work_portfolio_filter .work_portfolio_f_item
                    .post-comment .reply a:hover,
                    .comment-form .form-control:focus,
                    .service_video .video-play,
                    .single_product_item .product_quary.pr_red,
                    .filter_slider_area .filter_content .button_b,
                    .por_pagination_btn:hover span,
                    .search-form .form-control:focus,
                    .filter_slider_area .ui-slider .ui-slider-handle,
                    .filter_slider_area .filter_content .button_b,
                    .post-comment .avatar img,
                    .more_btn,
                    .feature-box-three .btn-sm,
                    .testimonial_two_yellow .testimonial-item .img:after,
                    .btn.read-more,
                    #contact-form .btn.btn-candy:hover, .comment-form .btn.btn-candy:hover,
                    .work_portfolio_filter .work_portfolio_f_item,
                    .woocommerce span.onsale
                    ',
            ),
			'default'   => '#ff5f6d',
		),
	)
));